### ISSUE TITLE
request-attributes sample in integration-all-configs

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [Dynatrace/dynatrace-configuration-as-code#111]
**Describe the bug**
`integration-all-configs` is missing an example for a request attribute.

**Solution**
Add example code to [integration-all-configs](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/tree/main/cmd/monaco/test-resources/integration-all-configs/project) for `request-attributes`

**Comment by UnseenWizzard** [comment]
A sample was added with #1050
