### ISSUE TITLE
Monaco 2.10.0 - incorrect order deploying network zones

### ISSUE THREAD

**Issue by evaldasc** [Dynatrace/dynatrace-configuration-as-code#1356]
During deployment Monaco tries to deploy management:network-zone before builtin:networkzones
it fails on first run with following message:
`Failed to send HTTP request: (HTTP 400)!     Response was: Not allowed because network zones are disabled`
it is successful on rerun

**How to reproduce**
- new environment with network zones disabled
- management:network-zone set to enable in /builtinnetworkzones/config.yaml+ json
- a network zone described network-zone/config.yaml + json

**Expected behavior**
monaco turns on network zones setting and sets them up

Monaco 2.10.0

**Comment by warber** [comment]
Hi @evaldasc Thanks, for reaching out. 
You are right, this kind of "static" dependency between that setting and the network zone config is not taken into consideration by monaco. If the ordering is relevant to you you would need to add a "fake" dependency between these two config entities. However, I agree that it would be a better UX if monaco would just take care of that, by knowing that the network zone setting must come first.
