### ISSUE TITLE
monaco account : Error: failed to fetch supportedPermissions

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [Dynatrace/dynatrace-configuration-as-code#1520]
**Describe the bug**
Try to deploy account settings with the ```monaco account``` command gives a error message:
```
Error: failed to fetch supportedPermissions: unable to fetch supported permission ids: failed to parse PermissionsDto field
```
Maybe missing permissions for the OAuth Client, but these aren't documented?

**How to reproduce**
- Create monaco Oauth Client for account management with policies:
```
account-idm-read, account-idm-write, account-env-read, account-env-write, iam-policies-management, iam:policies:write, iam:policies:read, iam:bindings:write, iam:bindings:read, iam:effective-permissions:read
```
- create basic account configuration e.g. with a group
- try to deploy the group with
```
monaco account deploy -m manifest.yaml -p <project> -a <account>
```

**Expected behavior**
Correct deployment of the account assets

**Log output**
```
2024-07-04T15:49:11+02:00       info    Monaco version 2.14.2
2024-07-04T15:49:11+02:00       info    Loading manifest "manifest.yaml". Restrictions: groups=[], environments=[]
2024-07-04T15:49:12+02:00       error   Error: failed to fetch supportedPermissions: unable to fetch supported permission ids: failed to parse PermissionsDto field
```

**Environment (please complete the following information):**
 - OS: macOS
 - Monaco 2.14.2

**Comment by warber** [comment]
Hi @reinhard-brandstaedter,

Please upgrade to [v2.14.3](https://github.com/Dynatrace/dynatrace-configuration-as-code/releases/tag/v2.14.3) which contain a fix for this bug.

**Comment by reinhard-brandstaedter** [comment]
@warber oh i missed that upgrade, fixed it!
