### ISSUE TITLE
It would be great to support creating ParameterSets and Rules of the failure detection api. (Configuration API v1)

### ISSUE THREAD

**Issue by didiladi** [Dynatrace/dynatrace-configuration-as-code#280]
It would be great to support creating ParameterSets and Rules of the failure detection api. (Configuration API v1)

This would be 
`PUT api/config/v1/service/failureDetection/parameterSelection/parameterSets/{id}`
and
`PUT api/config/v1/service/failureDetection/parameterSelection/rules/{id}`

We have to make those steps by hand at the moment and it would be great to support this in monaco.

_Originally posted by @chanusch in https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/discussions/278_

**Comment by tatomir146** [comment]
@chanusch as you already started working on this, can you pls grab this ticket? Thanks!
