### ISSUE TITLE
Need to download dashboard share settings (api/config/v1/dashboards/{id}/shareSettings) 

### ISSUE THREAD

**Issue by andymanning** [Dynatrace/dynatrace-configuration-as-code#337]
**Describe the solution you'd like**
Need to be able to get the dashboard sharing configuration (api/config/v1/dashboards/{id}/shareSettings). It doesn't match the criteria of an 'easy-to-add api' as it only returns an id , not a name.

**Comment by UnseenWizzard** [comment]
closing this in favor of the more issue to support Dashboard share settings #378
