### ISSUE TITLE
Monaco 2.0 deprecation

### ISSUE THREAD

**Issue by tatomir146** [Dynatrace/dynatrace-configuration-as-code#352]
Just a reminder for deprecation features:
- `application` config will be replaces with `application-web`
- NEW_CLI becomes standard

**Comment by tatomir146** [comment]
Improve warning message:
```
log.Warn("CONFIG_V1 environment var detected!")
log.Warn("Please convert your config to v2 format, as the migration layer will get removed in one of the next releases!")
```

**Comment by didiladi** [comment]
Discuss: Do we need a default manifest name when converting configs?

This does not work:
```
monaco convert -v --environments cmd/monaco/v2/legacy/test-resources/test-environments.yaml --outputFolder cmd/monaco/v2/test-resources/integration-all-configs cmd/monaco/v2/legacy/test-resources/integration-all-configs
```

But this does:
```
monaco convert -v --environments cmd/monaco/v2/legacy/test-resources/test-environments.yaml --manifestName manifest --outputFolder cmd/monaco/v2/test-resources/integration-all-configs cmd/monaco/v2/legacy/test-resources/integration-all-configs
```

**Comment by didiladi** [comment]
Blocker: Check if we have a version for the manifest config.

**Comment by didiladi** [comment]
Idea: Use a yaml schema for the new config format: https://developers.redhat.com/blog/2020/11/25/how-to-configure-yaml-schema-to-make-editing-files-easier#

Question: Is this currently possible using our new config (static properties used for parameters?)

**Comment by CruzanCaramele** [comment]
remove **next** from monaco output command
provide an explanation on what the **convert** command does in the same output as mentioned above
