### ISSUE TITLE
Command line snippets in documentation include prompt as well as command output when copied

### ISSUE THREAD

**Issue by arthurpitman** [Dynatrace/dynatrace-configuration-as-code#375]
**Describe the bug**
Command line snippets in the documentation include prompt (e.g. `$ `) as well as all output when copied. This limits the usefulness of the documentation.

**How to reproduce**
- Navigate to a documentation page, e.g. https://dynatrace-oss.github.io/dynatrace-monitoring-as-code/installation
- Copy a command , e.g. to _make the binary executable_
- Paste into a terminal.
  - Pasted command is `$ chmod +x monaco` (which cannot be run)

**Expected behavior**
- The copied and pasted command can be run directly, with little to no modification.
- Commands are split into logical units designed to be copied and pasted together.
- Commands are separate from the output they produce.

**Log output**
Running copied and pasted commands currently typically results in `$: command not found`

**Environment:**
 - OS: Linux
 - Tool version: v1.6.0

**Additional information**
An example approach to solving this issue: https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/install

**Comment by UnseenWizzard** [comment]
Hi @arthurpitman thanks for reporting this

In addition to this, the windows installation documentation is also incomplete

**Comment by UnseenWizzard** [comment]
resolved in v2 snippets (https://www.dynatrace.com/support/help/manage), won't fix for v1 documentation
