### ISSUE TITLE
Support Dashboard sharing settings API

### ISSUE THREAD

**Issue by UnseenWizzard** [Dynatrace/dynatrace-configuration-as-code#378]
Dashboard sharing settings are now available as an API in EAP 

monaco should support the API to allow automatically sharing dashboards, instead of still requiring manual/UI interaction.

Notably the API is part of the Dashboard API (under /dashboards/{id}/sharing) and requires the ID of the dashboard while only offering GET and PUT. 

These configurations will thus usually depend on a dashboard configuration directly, and not follow the "POST if no config exists/PUT if exists" patter of regular configuration.

**Comment by patrickpichler** [comment]
Related to #337

**Comment by Laubi** [comment]
Already supported in Monaco
