### ISSUE TITLE
[2.0-next] Improve error report for deployment

### ISSUE THREAD

**Issue by patrickpichler** [Dynatrace/dynatrace-configuration-as-code#382]
As of right now, the new error report simply groups the errors 
by project/api/config and prints them. It is not really nice to look
at. We should come up with a better way to print it.

**Comment by didiladi** [comment]
Outcome of the discussion: What we want is to improve teh default log message to incluse the following content:

```
<Date/Time> <Loglevel> <environment> <ConfigType> <ConfigName> <Message + file>
```

E.g.:

```
2021-09-21 00:51:48 ERROR igo0815 application-web my-app Syntax Error in json: No name defined (config file /project/application-web/my-app.json)  
```

**Comment by UnseenWizzard** [comment]
summary of open sub-tasks: 
- [ ] introduce human readable Type for all our Errors
- [ ] improve upload error format
- [ ] introduce a "Context Aware" logger that is passed into modules and prefixes log lines to fit `env configcoord MSG` format
