### ISSUE TITLE
Naming unification

### ISSUE THREAD

**Issue by tatomir146** [Dynatrace/dynatrace-configuration-as-code#422]
Check that:
- we use same flags for all commands
- name command go files accordingly (e.g. deploy/cmd.go should be named deploy/deploy.go)
- normalise help text e.g.
```
ArgsUsage: "<path to monaco project folder to convert>",
ArgsUsage: "[working directory]",
```
- remove `v2` from package names. `v2` is default version now

**Comment by CruzanCaramele** [comment]
the explanation of flags of the output of running **monaco download** are incorrect

```
OPTIONS:
   --verbose, -v                           (default: false)
   --environments value, -e value          Yaml file containing environment to deploy to
   --specific-environment value, -s value  Specific environment (from list) to deploy to
   --downloadSpecificAPI value, -p value   Comma separated list of API's to download
   --help, -h                              show help (default: false)
```

**Comment by patrickpichler** [comment]
There is actually a difference between arguments in `[]` and `<>`. Arguments
in `<>` are required whereas `[]` are optional. I have no idea how we could make
this clearer to the end user.

**Comment by UnseenWizzard** [comment]
flags unified with 2.0 commands
