### ISSUE TITLE
Path resolution for dependencies in monaco 1.6 is not working across OS

### ISSUE THREAD

**Issue by drqc** [Dynatrace/dynatrace-configuration-as-code#463]
When using the same Monaco project with the same folder structure the dependency resolution works differently as seen in the image, this blocks the reusability of monaco projects across different OS.

On the left of the image is Monaco exe running on windows, on the right running on Linux. Same project, same folder structure, same relative path reference.

This might be solved on monaco 2.0. I will start testing the same scenario with the next branch

![image](https://user-images.githubusercontent.com/70604844/139350154-95878011-4eb4-4a7f-9988-24778bb4a090.png)

**Comment by UnseenWizzard** [comment]
monaco 2.0 un-ties the reference format from filepaths, instead allowing to define them as 'project', 'type' and 'config id' in a dedicated reference parameter. 
Additionally, loading happens from a 'manifest.yaml' downwards, not the location monaco is executed in
