### ISSUE TITLE
Error getting configs from API calculated-metrics-log

### ISSUE THREAD

**Issue by bentomi** [Dynatrace/dynatrace-configuration-as-code#584]
**Error description**

Running monaco with the new CLI cannot get the configs for calculated-metrics-log.

**How to reproduce**

Run `NEW_CLI=1 monaco download --environments environments.yaml`.

The contents of `environments.yaml`:
```
development.sandbox:
  - name: sandbox
  - env-token-name: DT_TOKEN
  - env-url: https://ogx73077.live.dynatrace.com/
```

**Expected behavior**

The tool runs without errors.

**Log output**

```
2022-03-23 10:29:33 ERROR error getting client list from api calculated-metrics-log Failed to get existing configs for api calculated-metrics-log (HTTP 400)!
    Response was: {"error":{"code":400,"message":"You are using the new log monitoring solution. Old API endpoints are disabled."}}
2022-03-23 10:29:33 ERROR error getting configs from API calculated-metrics-log %!v(MISSING)
```

**Environment (please complete the following information):**

 - OS: macOs Monterey (but it happens on Linux too)
 - Tool version: v1.7.0
 - Dynatrace cluster version: 1.237.176.20220321-143738

**Comment by tobigremmer-dt** [comment]
Running into the same issue. This seems to be related to environments where log monitoring v2 is enabled.

**Comment by UnseenWizzard** [comment]
Hi @bentomi , Hi @tobigremmer-dt ,

sorry for the late reply on this. 

This is indeed relate to log monitoring v2 as @tobigremmer-dt mentioned. 
log monitoring v2 is using a new type of configuration API that is sadly currently not supported by monaco. 

You will have to work around this error by not deploying log metrics to environments using logs v2 - by [skipping them on deployment](https://dynatrace-oss.github.io/dynatrace-monitoring-as-code/configuration/yaml_config#skip-configuration-deployment)

**Comment by UnseenWizzard** [comment]
Monaco 2.0 supports the 'legacy log monitoring' `calculated-metrics-log` as well as the current log monitoring configuration via Settings.

Not that downloads will still attempt to download `calculated-metrics-log` and show this error, as we have no way of checking what version of log monitoring is active on an environment
