### ISSUE TITLE
Delete non-unique name entities when they are unique

### ISSUE THREAD

**Issue by tobigremmer-dt** [Dynatrace/dynatrace-configuration-as-code#661]
Alongside https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/pull/654 a bug was fixed to not randomly delete entities (e.g. dashboards) when there are more than one with the same name. The current implementation skips such configurations all together.

An improvement to this would be to check how many entities exist with a potentially non-unique name. If there's only a single result it can be safely deleted otherwise skipped.

**Comment by UnseenWizzard** [comment]
resolved in 2.0
