### ISSUE TITLE
Support for Dynatrace Managed configuration as code

### ISSUE THREAD

**Issue by kristofre** [Dynatrace/dynatrace-configuration-as-code#67]
Apart from using monaco to configure a Dynatrace Environment configuration, it would also be great to have the ability to configure a Dynatrace Managed cluster.

**Describe the solution you'd like**
The ability to specify a managed cluster and token, and then configure the cluster using monaco

Endpoints that come to mind:

- CRUD of a tenant
- CRUD of Users/Groups
- Cluster configuration itself

**Comment by rszulgo** [comment]
I'd love to take this one!

**Comment by didiladi** [comment]
Hey @rszulgo. Cool, thank you! I assigned the ticket to you.

I believe it makes sense to talk about the `CRUD of Users/Groups` beforehand. As you have seen, we also have #78 in our backlog. It would be fantastic to have a unified solution here, which works for both SaaS and Managed.

**Comment by UnseenWizzard** [comment]
Closing this as Managed Cluster configuration is currently out of scope for configuration-as-code, but may be tackled with internal planning in the future.
