### ISSUE TITLE
Directory file name error at download in Windows

### ISSUE THREAD

**Issue by mizso74** [Dynatrace/dynatrace-configuration-as-code#825]
**Describe the bug**
During the download process directories did not create because of not allowed character (":") in the directory name.

**How to reproduce**
C:\MONACO2>monaco2 download manifest manifest.yaml peti_environment
2023/02/19 17:02:19 INFO  Dynatrace Configuration as Code v2.0.0-rc.4
2023/02/19 17:02:19 INFO  Downloading from environment 'https://ssv731.dynatrace-managed.com:9999/e/a04c8dd0-bed4-4065-b64e-35a74924e65b' into project 'project_peti_environment'

**Expected behavior**
During the download process directories should created with allowed characters (eg. except ":" )

**Log output**
2023/02/19 17:02:21 WARN  Downloaded setting of schema "builtin:logmonitoring.log-dpp-rules" will be discarded. Reason: "[Built-in] load_balancer:haproxy:error" cannot be managed via configuration as code
2023/02/19 17:02:21 WARN  Downloaded setting of schema "builtin:logmonitoring.log-dpp-rules" will be discarded. Reason: "[Built-in] load_balancer:haproxy:default" cannot be managed via configuration as code
2023/02/19 17:02:21 WARN  Downloaded setting of schema "builtin:logmonitoring.log-dpp-rules" will be discarded. Reason: "[Built-in] cloud:azure:common" cannot be managed via configuration as code
2023/02/19 17:02:21 INFO  Resolving dependencies between configurations
2023/02/19 17:02:22 ERROR mkdir download_2023-02-19-170221\project_peti_environment\builtin:process-group.detection-flags: The directory name is invalid.
2023/02/19 17:02:22 ERROR mkdir download_2023-02-19-170221\project_peti_environment\builtin:monitoredentities.generic.relation: The directory name is invalid.
2023/02/19 17:02:22 ERROR mkdir download_2023-02-19-170221\project_peti_environment\builtin:anomaly-detection.infrastructure-disks: The directory name is invalid.
2023/02/19 17:02:22 ERROR mkdir download_2023-02-19-170221\project_peti_environment\builtin:container.technology: The directory name is invalid.
2023/02/19 17:02:22 ERROR mkdir download_2023-02-19-170221\project_peti_environment\builtin:rum.web.browser-exclusion: The directory name is invalid.
2023/02/19 17:02:22 ERROR mkdir download_2023-02-19-170221\project_peti_environment\builtin:mainframe.txstartfilters: The directory name is invalid.
2023/02/19 17:02:22 ERROR mkdir download_2023-02-19-170221\project_peti_environment\builtin:sessionreplay.web.privacy-preferences: The directory name is invalid.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Tool version v2.0.0-rc.4

**Additional context**

**Comment by UnseenWizzard** [comment]
Thanks for reporting this @mizso74! We'll make sure to address this with the official release. 

As a workaround for now, you could use the Linux version in WSL
