### ISSUE TITLE
Monaco 2.0 - URL mismatch during direct download

### ISSUE THREAD

**Issue by GarrettHaines** [Dynatrace/dynatrace-configuration-as-code#925]
I am attempting a direct download on Monaco 2.0 using "monaco download direct [URL] [token]" but am getting this issue:
![issue](https://user-images.githubusercontent.com/70733202/228375423-5899be31-eaf3-4492-8b38-ea6966588e13.jpg)

As you can see, a request is being made to "URL/api/v1/config/..." as I have highlighted. However, it appears the config API for our tenant is formatted as "URL/api/config/v1/..." as shown below:
![issue pt 2](https://user-images.githubusercontent.com/70733202/228375039-190f34fa-c6f5-4fe6-b552-480dc55c829f.jpg)

Is this a bug? Could it have anything to do with the fact that I am using a managed deployment? I need to transfer our managed tenant configs/settings over to a SaaS-based tenant as painlessly as possible, if possible. We have hundreds of management zones, application detection rules, and more that need to be transferred.

Thank you!

**Comment by GarrettHaines** [comment]
Hello @UnseenWizzard,
Did you notice the difference in the path that I mentioned? A request is being made to "/api/**v1/config**/..." but shouldn't it be "/api/**config/v1**/..."? I have not configured a manifest, as I am trying to download the configurations directly.

**Comment by UnseenWizzard** [comment]
Hi @GarrettHaines, 

I did notice that. I hope you noticed the API it is trying to query, as I pointed out in my reply above:

> the API that is being called in this specific case is the **Environment API v1**.
> It has a /config/clusterversion endpoint, thus the confusing /api/v1/config/...

What I said above about verifying that the machine can actually resolve the host or trying the IP instead applies to direct downloads as well of course. 
If you try the IP instead of hostname you'd just have to pass it as the URL argument rather than write it into the manifest of course.

> The issue seems to be that the hostname of your managed environment can't be resolved.
> Can you ping it from the same machine? I'd assume you see the same issue there.

**Comment by GarrettHaines** [comment]
Thank you!
