### ISSUE TITLE
Where do I get Monaco JSON config parameters documentation

### ISSUE THREAD

**Issue by krishnad1982** [Dynatrace/dynatrace-configuration-as-code#967]
Is any documentation available regarding the Dynatrace Monaco JSON config parameters? 
I want to check what mandatory or optional parameters are.

**Comment by UnseenWizzard** [comment]
For the JSON content please refer directly to the Dynatrace API documentation: 
For Configuration types: 
https://www.dynatrace.com/support/help/dynatrace-api

For Settings Schemas: 
https://www.dynatrace.com/support/help/dynatrace-api/environment-api/settings/schemas

And refer to the reference on how Monaco's types match to APIs exactly: 
https://www.dynatrace.com/support/help/manage/configuration-as-code/reference/supported-configuration
