### ISSUE TITLE
Monaco 2.0.1 -  Failed to deploy BitBucketNodeRemovedFromCluster - metric key is not child of 'calc:log.

### ISSUE THREAD

**Issue by GarrettHaines** [Dynatrace/dynatrace-configuration-as-code#970]
Hello,
I am using Monaco 2.0.1.
When I try to deploy my config, I am getting this error after some configs are uploaded:
<img width="661" alt="image" src="https://user-images.githubusercontent.com/70733202/233729100-4510a982-a24c-45c2-9b95-a3893eea6431.png">
Why is this happening? :(

**Comment by UnseenWizzard** [comment]
Hi @GarrettHaines, 
This is not a monaco error or bug, but an error reported by the Dynatrace API* - as the message states, something is wrong with the metric key in that configuration

> Metric key is not child of 'calc:log."

Please check your configuration (JSON and YAML) and the documentation for the calculated log metrics API to fix the configuration.  

I don't know details about this API but I'd start looking at whether your new metric's key starts with `calc:log` - but that's just a guess based on the error.

*which you can tell by the "failed to deploy", "response was" and JSON formatted error message, which is the Dynatrace API response
