### ISSUE TITLE
Question - Best Structure for 100s of custom metric events

### ISSUE THREAD

**Issue by kbocock-krg** [Dynatrace/dynatrace-configuration-as-code#981]
**Before you proceed**
We are happy about your enhancement proposal, but we would like to discuss this with you. Please make sure you've opened a [discussion](https://github.com/dynatrace/dynatrace-configuration-as-code/discussions) and are creating this feature/improvement request as a result of it. Make sure to link discussion here. 

**Is your feature request related to a problem? Please describe.**
We are working to create what we deem to be necessary shared services metrics and alerts for all of the 15+ shared services in our kubernetes clusters. We are seeing several DRY concerns in trying to structure this and wondering if we can post with monaco an array of anomoly-detection metric events which would keep our config file clean. Additionally if the templates yaml parameter in this file was a list this could also prove most useful. Most of the parameters we have are repeated. 

**Describe the solution you'd like**
What do you suggest as a clean IaC structure for creating 100s of these alerts for our clusters? Note: The notification web hooks will be the same per environment but will change in prod. 

**Describe alternatives you've considered**
- making template a list of json files in the config.yaml
- Making the json file an array
- tried *.json in the template of the config.yaml
- Tried different folders within our service folder where Proj --> Prometheus --> n Anomoly metric events. 

**Additional context**
Add any other context about the feature request here.

**Comment by kbocock-krg** [comment]
What is the license of monaco?  Can we modify the code to allow a config to allow a list of templates and remove the need for unique id.

**Comment by UnseenWizzard** [comment]
Apache 2.0
https://github.com/Dynatrace/dynatrace-configuration-as-code/blob/main/LICENSE

You're very welcome to fork and modify to your needs! 

Just be aware that the config ID (or project:type:id "coordinate" tuple) is used both for identifying configs internally for references and to identify Settings 2.0 configurations (as well as upcoming Platform feature configs) on Dynatrace. 

So breaking the config ID uniqueness constraint comes with quite some added dangers. 

For a list of templates, our internal idea would have been a map of `template ID -> file`, making the template ID usable as part of still generating unique identifiers. And still allowing for files to change without impacting IDs.

If you have a good idea/solution for this that does not break current constraints, we're also always happy about contributions!  :)
